export * from './home/home.component';
export * from './assignments/assignments.component';
export * from './gamers/gamers.component';
export * from './navbar/navbar.component';
export * from './not-found/not-found.component';
export * from './game-card-list/game-card-list.component';
export * from './game-card/game-card.component';
export * from './tic-tac-toe/tic-tac-toe.component';
export * from './tic-tac-toe-cell/tic-tac-toe-cell.component';
